#! /bin/bash

set -e

VERSION=`cat VERSION`

RELEASE_DIR=/tmp/qinxh/release_falcon_eye
RELEASE_DIR_FILES=$RELEASE_DIR/falcon_eye
rm -rf $RELEASE_DIR
mkdir -p $RELEASE_DIR_FILES

export GOROOT=/home/ulric/go
export GOPATH=/home/ulric/code/gowork
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH

cd $GOPATH/src/github.com/ulricqin/falcon-eye
go install

cp -r VERSION startup cfg.ini public templates $RELEASE_DIR_FILES
cp $GOPATH/bin/falcon-eye $RELEASE_DIR_FILES/falcon_eye

cd $RELEASE_DIR
tar zcf falcon_eye-$VERSION.tar.gz falcon_eye

echo "target save at $RELEASE_DIR/falcon_eye-$VERSION.tar.gz"

